apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-labels
  namespace: dev
spec:
  validationFailureAction: enforce
  rules:
  - name: check-for-labels
    match:
      resources:
        kinds:
        - Pod
    preconditions:
    - key: "{{ request.operation }}"
      operator: Equals
      value: CREATE
    validate:
      message: "The label `owner` is required."
      pattern:
        metadata:
          labels:
            owner: "?*"